name    'lbetz-tomcat'
version '0.2.3'
source 'https://github.com/lbetz/puppet-tomcat'
author 'Lennart Betz'
license 'GPL v2'
summary 'Setup and configure Apache Tomcat on RedHat/CentOS'
description 'Setup and configure Apache Tomcat on RedHat/CentOS'

dependency 'puppetlabs/stdlib', '>=3.2.1'
dependency 'puppetlabs/concat', '>=1.0.1'
