name    'lbetz-tomcat'
version '0.2.0'
source 'https://github.com/lbetz/netways-tomcat'
author 'Lennart Betz'
license 'GPL v2'
summary 'Setup and configure Apache Tomcat on RedHat/CentOS'
description 'Setup and configure Apache Tomcat on RedHat/CentOS'

'puppetlabs/stdlib' >= '3.2.1'
'puppetlabs/concat' >= '1.0.1'
